[package]
name = "bevy_magnetite"
version = "0.1.0"
edition = "2024"
authors = [
    "Jonathan Schmittat",
    "Abdurahman Algheb <abdurahmanalgheb@gmail.com>"
]
exclude = [".github", ".gitignore", "scripts"]

[dependencies]
bevy = "0.17.3"
